### ISSUE TITLE
PR 15 introduced unintended pointer vs value return changes

### ISSUE THREAD

**Issue by jasdel** [jmespath/go-jmespath#20]
In #15 it looks like some unintended changes where introduced. I scalar types are not being returned as values types even if the field for that value was a pointer type. Structs still are being returned as pointer types if they originally were.

This issue was reported to us in aws/aws-sdk-go#535 as it is breaking some functionality for those not using vendoring with the SDK.

**Comment by jamesls** [comment]
#15 has been reverted.
