### ISSUE TITLE
is this repo being maintained?

### ISSUE THREAD

**Issue by tve** [jmespath/go-jmespath#24]
A simple valid looking pull request open for months, two issues unanswered for months, no commit for months... Is this repo being maintained or is it abandon-ware?

**Comment by jamesls** [comment]
Yes it is being maintained.  Sorry about missing the earlier pull request, it simply fell under the radar.

**Comment by jamesls** [comment]
I should mention, please feel free to ping me if I do miss issues.  I try to stay on top of them, but with the various repos spread across various orgs, I don't always do a great job of keeping up to date.
