### ISSUE TITLE
Is this project still maintained? 

### ISSUE THREAD

**Issue by mosajjal** [jmespath/go-jmespath#95]
Hi, 

looking into one of my AWS project's dependency tree; looks like this project is the oldest, and `github.com/aws/aws-sdk-go` uses it.

**Comment by springcomp** [comment]
This project is definitely [still maintained](https://github.com/jmespath/jmespath.site/issues/94#issuecomment-1136192269), but some might say it has a [very slow pace](https://github.com/jmespath/jmespath.site/issues/94). 😉

That’s why at [JMESPath Community](https://github.com/jmespath-community/go-jmespath) we try and take it where it’s currently left off and try and bring improvements and requests from the community, while still adhering to a proper governance model.

**Comment by mosajjal** [comment]
I think this project looks feature-complete. Just needs to be freeze-maintained so dependencies are up-to-date. the fact that AWS is leveraging this in the SDK and because of it all subsequent projects have massive dependency tree is the main issue.
